name: Build Nanobyte OS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo wget \
                            nasm mtools python3 python3-pip python3-parted scons dosfstools libguestfs-tools qemu-system-x86

    - name: Install Python requirements
      run: python3 -m pip install -r requirements.txt

    - name: Prepare toolchain directory
      run: mkdir -p ../.toolchains

    - name: Build toolchain
      run: scons toolchain

    - name: Run libguestfs-test-tool
      run: libguestfs-test-tool

    - name: Build the OS with libguestfs debugging
      run: |
        export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
        scons

    - name: Upload built files
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: nanobyte-os-build
        path: build/
